# Generated by Django 5.1.1 on 2024-10-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0002_cash_entry_delete_cash_in_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_entry',
            name='tran_plat',
            field=models.CharField(blank=True, choices=[('phonepe', 'PhonePe'), ('googlepay', 'Google Pay'), ('paytm', 'Paytm')], max_length=50, null=True),
        ),
    ]
